# Generated by Django 2.1.7 on 2019-02-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('email_user', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('order_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('share_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('mode', models.CharField(max_length=4)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Client')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('user_name', 'order_no')},
        ),
    ]
